controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_yaw
      - shoulder_pitch
      - elbow_pitch
      - wrist_pitch
      - wrist_roll
  - name: fake_gripper_controller
    joints:
      - finger_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: zero